# Generated by Django 4.2.4 on 2023-08-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='marketitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
