# Generated by Django 4.2.4 on 2023-08-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_market_updated_at_marketitems_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='name',
            new_name='market_name',
        ),
    ]
